# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.Client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('phase_one_project', models.BooleanField(default=True)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('discovery_start_date', models.DateField(blank=True, null=True)),
                ('discovery_end_date', models.DateField(blank=True, null=True)),
                ('foundation_build_start_date', models.DateField(blank=True, null=True)),
                ('foundation_build_end_date', models.DateField(blank=True, null=True)),
                ('align_start_date', models.DateField(blank=True, null=True)),
                ('align_end_date', models.DateField(blank=True, null=True)),
                ('e2e_build_start_date', models.DateField(blank=True, null=True)),
                ('e2e_build_end_date', models.DateField(blank=True, null=True)),
                ('e2e_start_date', models.DateField(blank=True, null=True)),
                ('e2e_end_date', models.DateField(blank=True, null=True)),
                ('parallel_build_start_date', models.DateField(blank=True, null=True)),
                ('parallel_build_end_date', models.DateField(blank=True, null=True)),
                ('parallel_start_date', models.DateField(blank=True, null=True)),
                ('parallel_end_date', models.DateField(blank=True, null=True)),
                ('gold_build_start_date', models.DateField(blank=True, null=True)),
                ('gold_build_end_date', models.DateField(blank=True, null=True)),
                ('first_payroll', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Client')),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Methodology')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color_code', models.CharField(max_length=7)),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WDModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.ProjectPhase'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.ManyToManyField(to='api.WDModule'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Status'),
        ),
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.Project'),
        ),
    ]
