# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wdmodule',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='wdmodule',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
