# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodology',
            options={'ordering': ('name',), 'verbose_name_plural': 'methodologies'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('client', 'project')},
        ),
        migrations.AlterModelOptions(
            name='phaseinfo',
            options={'ordering': ('project', 'start_date', 'end_date'), 'verbose_name': 'phase', 'verbose_name_plural': 'phases'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ('name',), 'verbose_name': 'project phase'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('name',), 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='tenantbuild',
            options={'ordering': ('name',), 'verbose_name': 'tenant build'},
        ),
        migrations.AlterModelOptions(
            name='tenantbuildinfo',
            options={'ordering': ('project', 'start_date', 'end_date'), 'verbose_name': 'build', 'verbose_name_plural': 'builds'},
        ),
        migrations.AlterModelOptions(
            name='testingcycle',
            options={'ordering': ('name',), 'verbose_name': 'testing cycle'},
        ),
        migrations.AlterModelOptions(
            name='testingcycleinfo',
            options={'ordering': ('project', 'start_date', 'end_date'), 'verbose_name': 'project testing cycle', 'verbose_name_plural': 'project testing_cycles'},
        ),
        migrations.AlterModelOptions(
            name='wdmodule',
            options={'ordering': ('order', 'name'), 'verbose_name': 'WD module'},
        ),
    ]
