# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181004_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wdmodule',
            options={'ordering': ('order', 'name')},
        ),
    ]
