# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181004_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('start_date', 'end_date'),
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='e2e_build_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='e2e_build_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='foundation_build_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='foundation_build_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gold_build_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gold_build_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parallel_build_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parallel_build_start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='kickoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Client'),
        ),
        migrations.AddField(
            model_name='project',
            name='builds',
            field=models.ManyToManyField(to='api.TenantBuild'),
        ),
    ]
