# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181004_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbuild',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantbuild',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
